### PR TITLE
適配 mint

### PR DESCRIPTION
**Pull request by yume190**
讓 SPM 專案能透過 mint 安裝，`mint install woshiccm/Pecker`

### CODE REVIEW

**Comment by woshiccm** [comment]
Cool! Could you also update README mint supported

**Comment by woshiccm** [comment]
If it is not convenient, I will update the README later

**Comment by yume190** [comment]
Why use `--disable-sandbox` in Makefile build, can you give me the reason?
能說明一下為什麼在 build 時需要下 `--disable-sandbox` 這項參數？

**Comment by woshiccm** [comment]
So I can access a users home directory

**Pull request merged**
